default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: glencina
  password: glencina
  
development:
  <<: *default
  database: clothes_shop_development
  
test:
  <<: *default
  database: clothes_shop_test

production:
  <<: *default
  database: clothes_shop_production
